### PR TITLE
Added onClick() events for the AUX buttons.

### LINKED ISSUE #2: Add onClick() events for the AUX buttons
## 📦  Project: UI Settings

This issue is a good first issue for those looking to get into git, project collaboration, or html/javascript in general.   It is tied to the respective [project page](https://github.com/users/aaronmaynard/projects/1) and will be automatically sorted.
❤️ Thanks for helping!

## 📋  Issue:

The auxiliary buttons need to be able to do something! For now, make them display a message in the browser console.log(), informing which button was pressed.  The functions will later be used to send ROS messages, but that's an issue for another time.

Here

Non-ROS based code such as this can be added in /js/mod.js.  Each button in index.html that needs an onclick function is can be found below.

```
<!-- CENTRAL BUTTONS -->
<div class="auxButtons uiElement">
	<button class="buttonAux" onclick=""><span>Y</span><span>AUX 1</span></button>
	<br>
	<button class="buttonAux" onclick=""><span>X</span><span>AUX 2</span></button>
	<button class="buttonAux" onclick=""><span>B</span><span>AUX 3</span></button>
	<br>
	<button class="buttonAux" onclick=""><span>A</span><span>AUX 4</span></button>
</div>
```

#### Helpful Hint:
W3schools has a great tutorial on the onclick event. https://www.w3schools.com/jsref/event_onclick.asp 

## 👥  Contributing:

-  Comment in this issue that you would like to do it.
-  Open the ROSDashboard GitHub page and click the ★ Star and then ⑂ Fork buttons.
-  Once you've made sure all your changes work correctly and committed all your changes,
-  Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/ROSDashboard) and create a pull request for your changes.
-  Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #2)
-  Please <b>do not fix more than one issue at a time</b>. Your pull request should only fix what is described in this issue.

## 🆘  Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community.
If you need any help, feel free to ask below. We are always happy to help 😄

### PR DESCRIPTION
**Pull request by harshiiiit**
## PR Description

* [x] Added onClick() events, displays on the console which button is pressed.

## Issue fixed

Fixes #2

## Impacted parts

- Added auxButtons() function in mod.js
- Added id to each auxiliary button in index.html

### CODE REVIEW

**Comment by Girishbari** [comment]
hi @harshiiiit, I saw you already contributed to this project, will you please take time to answer me something as I am not able to run this project locally via Live server,
when I pressed onnect button it is giving me error with no proper description
image

**Comment by harshiiiit** [comment]
hi @Girishbari , well I was getting this error before I contributed. Even the master branch is giving this error, maybe someone from the team can help us with that. If you want to test the features I added click on the 'X' on the top right.

**Comment by Girishbari** [comment]
oh that was quite simple and it helped thx @harshiiiit

**Comment by aaronmaynard** [comment]
Hello @Girishbari, the reason for these errors is because the connection isnt being established with a ROS workspace. As @harshiiiit pointed out, you can ignore this error by pressing on the X

**Review by aaronmaynard — APPROVED** [review]

**Pull request merged**
